# Fill up the values, then rename file to application-secret.yml

facebook:
  client:
    clientId: --
    clientSecret: --

github:
  client:
    clientId: --
    clientSecret: --

reddit:
  client:
    clientId: --
    clientSecret: --